### ISSUE TITLE
OpenGL Cores

### ISSUE THREAD

**Issue by RobLoach** [heuripedes/nanoarch#5]
What would be required to allow for OpenGL cores?

**Comment by heuripedes** [comment]
Just implementing the RETRO_ENVIRONMENT_SET_HW_RENDER environment command. See sdlarch: https://github.com/heuripedes/sdlarch  It's mostly nanoarch but rewriten to use SDL stuff and it implements OpenGL core loading, but I am not certain if complex cores like mupen still work.

**Comment by RobLoach** [comment]
[sdlarch](https://github.com/heuripedes/sdlarch) looks pretty awesome! I'll jump over there. Thanks a lot!
