### ISSUE TITLE
Setting the resolution/framerate

### ISSUE THREAD

**Issue by sriramsk1999** [heuripedes/nanoarch#8]
Hello, I'm building a game streaming application using nanoarch ([llft-gaas](https://github.com/sriramsk1999/llft-gaas)) and I'm looking for a way to set the resolution and framerate.

I would be very grateful if I could be pointed in the right direction as to how to go about implementing this. I had a look at the `libretro.h` header and RETRO_SET_SYSTEM_ENVIRONMENT_AV_INFO seems to be the right callback though I am not sure how to call it. Am I correct in believing that I need to add a `case RETRO_SET_SYSTEM_ENVIRONMENT_AV_INFO` inside the `core_environment` function? 

Any guidance on how to implement this would be greatly appreciated!

**Comment by heuripedes** [comment]
The code in `core_environment` is called by the core directly, so if you want to *react* to resolution or timing changes triggered by the core that is the correct place to put your code, please take in consideration the comments around `SET_AV_INFO` and `SET_GEOMETRY` for details on what the core expects from the frontend. If you just want to change the window resolution you can check `video_configure`, there should be a call to a function that resizes the window.

**Comment by sriramsk1999** [comment]
Thank you for your response. Did you mean `glfwSetWindowSize`? I think it did the trick! I wanted to cut down on the resolution of the image I was sending for faster data transfer and from initial tests, I think this does the job. 

From your comment, I understand that `core_environment` is about reacting to the backend, which is not what I'm looking for. I'm wondering if there is a way for the frontend to tell the core what resolution and framerate to render at, and how that would be done.

**Comment by heuripedes** [comment]
If you want to transfer the video over the wire it might be a better idea to simply grab the picture from the raw bytes (data pointer) or the texture clipped to width x height within `video_refresh`. Next step is to encode and send (perhaps in another thread). Switching between multiple textures/buffers will also help with performance in this case. I've done something similar with RetroArch using the osmesa video driver (I wrote it) to render offscreen and pipe the video (over a file) to ffmpeg for encoding.

Asking the core to render at an especific size is not really or always possible. You see, most emulator cores simply render at the console's native resolutions. What nanoarch does is clip the texture to `last_frame_width x last_frame_height` and stretch it over the window however big it might be while maintaining the aspect ratio.

**Comment by sriramsk1999** [comment]
> If you want to transfer the video over the wire it might be a better idea to simply grab the picture from the raw bytes (data pointer) or the texture clipped to width x height within `video_refresh`

That is really helpful thank you! I've been using `glReadPixels` to get the data after rendering which is of course very wasteful, I'll see if I can get this working. As for encoding, I'm using `zlib` as it was simple to setup on both frontend and backend, and it seems to perform well. 

> Asking the core to render at an especific size is not really or always possible. You see, most emulator cores simply render at the console's native resolutions. What nanoarch does is clip the texture to `last_frame_width x last_frame_height` and stretch it over the window however big it might be while maintaining the aspect ratio.

Ah that's good to know, won't waste any more time trying to set the resolution then. 

Thank you again for all the help! I hope its okay if I open issues that are tangentially related to nanoarch, or perhaps contact you over email instead (sriramsk1999@gmail.com).
